### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Mortiferr** [Aliin/Symposium#14]
# General
- [x] Finish `CONTRIBUTING.md`
- [x] Fix labels for issues
- [x] Add milestones #11
- [x] Advertise this repo
- [ ] Translate - #12

# Front End
- [ ] Layout concept
- [x] Color scheme
- [ ] HTML for Posts and categories
- [ ] CSS for Posts and categories
- [ ] Make or find some graphics for Icons etc (if taken from the Internet, they MUST be licensed CC!)
- [ ] Javascript (when the HTML/CSS are finished)
- [ ] HTML, CSS, JS for submit post page

# Back end NEW
- [ ] Setup Database
- [ ] User Auth
- [ ] Modify and delete posts
- [ ] Modify and delete replies

#### Admin Panel
- [ ] User list with edit possible
- [ ] Default site settings

#### Font Page
- [ ] Display Categories and Posts on main page
- [ ] Allow users to submit a post
- [ ] Allow users to reply in post
- [ ] Allow guests to reply in post
- [ ] User list
- [ ] Search engine with looking for users, topics or posts
- [ ] User profile
- [ ] Let users leave

**We will keep adding new things.**

**Comment by Mortiferr** [comment]
@Aliin Instead of adding To-do list on the Wiki we should do it here that way it can be publically checked off.

**Comment by Aliin** [comment]
Okay, sorry. I'm learning still how to do all of this :)

**Comment by Aliin** [comment]
Okay, we'll just use this To-Do-List for rough outline from now on, the actual coordination and to-do-lists will be on Trello.

**Comment by Mortiferr** [comment]
Yeah, that's what it was intended to be, a public rough outline for those who were not on the Trello.
